## code to prepare `trial_types` dataset goes here

trial_types <- list(
  "animation" = "animation",
  "audio_button_response" = "audio-button-response",
  "audio_keyboard_response" = "audio-keyboard-response",
  "audio_slider_response" = "audio-slider-response",
  "call_function" = "call-function",
  "canvas_button_response" = "canvas-button-response",
  "canvas_keyboard_response" = "canvas-keyboard-response",
  "canvas_slider_response" = "canvas-slider-response",
  "categorize_animation" = "categorize-animation",
  "categorize_html" = "categorize-html",
  "categorize_image" = "categorize-image",
  "cloze" = "cloze",
  "external_html" = "external-html",
  "free_sort" = "free-sort",
  "fullscreen" = "fullscreen",
  "html_button_response" = "html-button-response",
  "html_keyboard_response" = "html-keyboard-response",
  "html_slider_response" = "html-slider-response",
  "iat_html" = "iat-html",
  "iat_image" = "iat-image",
  "image_button_response" = "image-button-response",
  "image_keyboard_response" = "image-keyboard-response",
  "image_slider_response" = "image-slider-response",
  "instructions" = "instructions",
  "maxdiff" = "maxdiff",
  "preload" = "preload",
  "reconstruction" = "reconstruction",
  "resize" = "resize",
  "same_different_html" = "same-different-html",
  "same_different_image" = "same-different-image",
  "serial_reaction_time" = "serial-reaction-time",
  "serial_reaction_time_mouse" = "serial-reaction-time-mouse",
  "survey_html_form" = "survey-html-form",
  "survey_likert" = "survey-likert",
  "survey_multi_choice" = "survey-multi-choice",
  "survey_multi_select" = "survey-multi-select",
  "survey_text" = "survey-text",
  "video_button_response" = "video-button-response",
  "video_keyboard_response" = "video-keyboard-response",
  "video_slider_response" = "video-slider-response",
  "virtual_chinrest" = "virtual-chinrest",
  "visual_search_circle" = "visual-search-circle",
  "webgazer_calibrate" = "webgazer-calibrate",
  "webgazer_init_camera" = "webgazer-init-camera",
  "webgazer_validate" = "webgazer-validate"
)

usethis::use_data(trial_types, overwrite = TRUE)
