library(tibble)

# tools ---------------------------------------
load_demo_trials <- function(type, fn = NULL) {
  if (is.null(fn)) fn <- demo_file(paste0("jspsych-", type, ".json"))
  jspsychread::read_jspsych(fn) %>% filter(trial_type == type)
}
expect_some_tibble <- function(x) {
  expect_true(is_tibble(x) && nrow(x) > 0)
}

# tests ---------------------------------------
test_that("Parsers run", {
  ##expect_some_tibble(load_demo_trials("html-keyboard-response"))

  #expect_some_tibble(load_demo_trials("animation"))
  # expect_some_tibble(load_demo_trials("audio‑button‑response"))
  # expect_some_tibble(load_demo_trials("audio‑keyboard‑response"))
  # expect_some_tibble(load_demo_trials("audio‑slider‑response"))
  # expect_some_tibble(load_demo_trials("browser‑check"))
  #expect_some_tibble(load_demo_trials("call-function"))
  # expect_some_tibble(load_demo_trials("canvas‑button‑response"))
  # expect_some_tibble(load_demo_trials("canvas‑keyboard‑response"))
  # expect_some_tibble(load_demo_trials("canvas‑slider‑response"))
  # expect_some_tibble(load_demo_trials("categorize‑animation"))
  # expect_some_tibble(load_demo_trials("categorize‑html"))
  # expect_some_tibble(load_demo_trials("categorize‑image"))
  # expect_some_tibble(load_demo_trials("cloze"))
  # expect_some_tibble(load_demo_trials("external‑html"))
  # expect_some_tibble(load_demo_trials("free‑sort"))
  # expect_some_tibble(load_demo_trials("fullscreen"))
  # expect_some_tibble(load_demo_trials("html‑audio‑response"))
  #expect_some_tibble(load_demo_trials("html-button-response"))
  #expect_some_tibble(load_demo_trials("html-keyboard-response"))
  # expect_some_tibble(load_demo_trials("html‑slider‑response"))
  # expect_some_tibble(load_demo_trials("iat‑html"))
  # expect_some_tibble(load_demo_trials("iat‑image"))
  #expect_some_tibble(load_demo_trials("image-button-response"))
  #expect_some_tibble(load_demo_trials("image-keyboard-response"))
  # expect_some_tibble(load_demo_trials("image‑slider‑response"))
  # expect_some_tibble(load_demo_trials("initialize‑microphone"))
  ##expect_some_tibble(load_demo_trials("instructions"))
  # expect_some_tibble(load_demo_trials("maxdiff"))
  # expect_some_tibble(load_demo_trials("preload"))
  # expect_some_tibble(load_demo_trials("reconstruction"))
  # expect_some_tibble(load_demo_trials("resize"))
  # expect_some_tibble(load_demo_trials("same‑different‑html"))
  # expect_some_tibble(load_demo_trials("same‑different‑image"))
  # expect_some_tibble(load_demo_trials("serial‑reaction‑time"))
  # expect_some_tibble(load_demo_trials("serial‑reaction‑time‑mouse"))
  # expect_some_tibble(load_demo_trials("sketchpad"))
  #expect_some_tibble(load_demo_trials("survey-html-form"))
  # expect_some_tibble(load_demo_trials("survey‑likert"))
  # expect_some_tibble(load_demo_trials("survey‑multi‑choice"))
  # expect_some_tibble(load_demo_trials("survey‑multi‑select"))
  # expect_some_tibble(load_demo_trials("survey‑text"))
  # expect_some_tibble(load_demo_trials("video‑button‑response"))
  # expect_some_tibble(load_demo_trials("video‑keyboard‑response"))
  # expect_some_tibble(load_demo_trials("video‑slider‑response"))
  # expect_some_tibble(load_demo_trials("virtual‑chinrest"))
  # expect_some_tibble(load_demo_trials("visual‑search‑circle"))
  # expect_some_tibble(load_demo_trials("webgazer‑calibrate"))
  # expect_some_tibble(load_demo_trials("webgazer‑init‑camera"))
  # expect_some_tibble(load_demo_trials("webgazer‑validate"))
})
