library(dplyr)
library(tibble)

# tools ---------------------------------------
load_demo_trials <- function(type, fn = NULL) {
  if (is.null(fn)) fn <- demo_file(paste0("jspsych-", type, ".json"))
  jspsychread::read_jspsych(fn) %>% dplyr::filter(trial_type == type)
}

# tests ---------------------------------------
test_that("Parsers run", {
  expect_equal(load_demo_trials("html-keyboard-response") %>% nrow(), 3)

  expect_equal(load_demo_trials("animation") %>% nrow(), 1)
  expect_equal(load_demo_trials("audio-button-response") %>% nrow(), 3)
  expect_equal(load_demo_trials("audio-keyboard-response") %>% nrow(), 4)
  expect_equal(load_demo_trials("audio-slider-response") %>% nrow(), 3)
  # expect_equal(load_demo_trials("browser-check"))
  expect_equal(load_demo_trials("call-function") %>% nrow(), 2)
  expect_equal(load_demo_trials("canvas-button-response") %>% nrow(), 6)
  expect_equal(load_demo_trials("canvas-keyboard-response") %>% nrow(), 5)
  expect_equal(load_demo_trials("canvas-slider-response") %>% nrow(), 2)
  expect_equal(load_demo_trials("categorize-animation") %>% nrow(), 1)
  expect_equal(load_demo_trials("categorize-html") %>% nrow(), 1)
  expect_equal(load_demo_trials("categorize-image") %>% nrow(), 1)
  expect_equal(load_demo_trials("cloze") %>% nrow(), 2)
  expect_equal(load_demo_trials("external-html") %>% nrow(), 1)
  expect_equal(load_demo_trials("free-sort") %>% nrow(), 4)
  expect_equal(load_demo_trials("fullscreen") %>% nrow(), 2)
  # expect_equal(load_demo_trials("html-audio-response"))
  expect_equal(load_demo_trials("html-button-response") %>% nrow(), 3)
  expect_equal(load_demo_trials("html-keyboard-response") %>% nrow(), 3)
  expect_equal(load_demo_trials("html-slider-response") %>% nrow(), 3)
  # expect_equal(load_demo_trials("iat-html"))
  # expect_equal(load_demo_trials("iat-image"))
  expect_equal(load_demo_trials("image-button-response") %>% nrow(), 8)
  expect_equal(load_demo_trials("image-keyboard-response") %>% nrow(), 16)
  expect_equal(load_demo_trials("image-slider-response") %>% nrow(), 7)
  # expect_equal(load_demo_trials("initialize-microphone"))
  expect_equal(load_demo_trials("instructions") %>% nrow(), 2)
  expect_equal(load_demo_trials("maxdiff") %>% nrow(), 2)
  expect_equal(load_demo_trials("preload") %>% nrow(), 3)
  expect_equal(load_demo_trials("reconstruction") %>% nrow(), 1)
  expect_equal(load_demo_trials("resize") %>% nrow(), 1)
  expect_equal(load_demo_trials("same-different-html") %>% nrow(), 1)
  expect_equal(load_demo_trials("same-different-image") %>% nrow(), 1)
  expect_equal(load_demo_trials("serial-reaction-time") %>% nrow(), 40)
  expect_equal(load_demo_trials("serial-reaction-time-mouse") %>% nrow(), 12)
  # expect_equal(load_demo_trials("sketchpad"))
  expect_equal(load_demo_trials("survey-html-form") %>% nrow(), 2)
  expect_equal(load_demo_trials("survey-likert") %>% nrow(), 2)
  expect_equal(load_demo_trials("survey-multi-choice") %>% nrow(), 2)
  expect_equal(load_demo_trials("survey-multi-select") %>% nrow(), 1)
  expect_equal(load_demo_trials("survey-text") %>% nrow(), 2)
  expect_equal(load_demo_trials("video-button-response") %>% nrow(), 2)
  expect_equal(load_demo_trials("video-keyboard-response") %>% nrow(), 2)
  expect_equal(load_demo_trials("video-slider-response") %>% nrow(), 2)
  # expect_equal(load_demo_trials("virtual-chinrest"))
  expect_equal(load_demo_trials("visual-search-circle") %>% nrow(), 4)
  # expect_equal(load_demo_trials("webgazer-calibrate"))
  # expect_equal(load_demo_trials("webgazer-init-camera"))
  # expect_equal(load_demo_trials("webgazer-validate"))
})
